spring:
  config:
    activate:
      on-profile: prod  # prod 프로파일
  datasource:
    url: jdbc:mysql://prod-db-server:3306/kidscafe
    username: root #사용자
    password: Admin123! #비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false  # View에서 DB 연결 방지
  jwt:
    secret: prod-secret-key
    expiration: 60*60*24  # 24시간 (초 단위)
  springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN